# Generated by Django 4.2.30 on 2026-04-12 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=255)),
                ('incident_type', models.CharField(max_length=255)),
                ('rescue_needs', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('current_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Warning', 'Warning'), ('Danger', 'Danger')], default='Normal', max_length=10)),
                ('trend', models.CharField(choices=[('Steady', 'Steady'), ('Rising', 'Rising'), ('Falling', 'Falling')], default='Steady', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='location',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='status',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='water_level',
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(default=datetime.datetime(2026, 4, 12, 18, 0, 5, 250043, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10),
        ),
    ]
